apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-db-storage-volume
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: postgres-db
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PG_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-db-storage-volume
              mountPath: /var/lib/postgresql/data
              subPath: postgres
